package com.helgolabs.trego.data.extensions

import com.helgolabs.trego.data.local.entities.DeviceTokenEntity
import com.helgolabs.trego.data.model.DeviceToken
import com.helgolabs.trego.data.sync.SyncStatus

fun DeviceToken.toEntity(): DeviceTokenEntity {
    return DeviceTokenEntity(
        tokenId = 0, // Local ID will be auto-generated by Room
        serverId = id, // Map model.id to entity.serverId
        userId = userId,
        fcmToken = fcmToken,
        deviceType = deviceType,
        createdAt = createdAt ?: "",
        updatedAt = updatedAt ?: "",
        syncStatus = SyncStatus.SYNCED
    )
}

fun DeviceTokenEntity.toModel(): DeviceToken {
    return DeviceToken(
        id = serverId, // Map entity.serverId to model.id
        userId = userId,
        fcmToken = fcmToken,
        deviceType = deviceType,
        createdAt = createdAt,
        updatedAt = updatedAt
    )
}