package com.helgolabs.trego.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6200EE)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBB86FC)
val md_theme_light_onPrimaryContainer = Color(0xFF3700B3)
val md_theme_light_secondary = Color(0xFF03DAC6)
val md_theme_light_onSecondary = Color(0xFF000000)
val md_theme_light_secondaryContainer = Color(0xFF018786)
val md_theme_light_onSecondaryContainer = Color(0xFF000000)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF000000)
val md_theme_light_error = Color(0xFFB00020)
val md_theme_light_onError = Color(0xFFFFFFFF)

val md_theme_dark_primary = Color(0xFFBB86FC)
val md_theme_dark_onPrimary = Color(0xFF3700B3)
val md_theme_dark_primaryContainer = Color(0xFF6200EE)
val md_theme_dark_onPrimaryContainer = Color(0xFFBB86FC)
val md_theme_dark_secondary = Color(0xFF03DAC6)
val md_theme_dark_onSecondary = Color(0xFF000000)
val md_theme_dark_secondaryContainer = Color(0xFF018786)
val md_theme_dark_onSecondaryContainer = Color(0xFF000000)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF121212)
val md_theme_dark_onSurface = Color(0xFFFFFFFF)
val md_theme_dark_error = Color(0xFFCF6679)
val md_theme_dark_onError = Color(0xFFB00020)