package com.helgolabs.trego.utils

import com.helgolabs.trego.utils.CurrencyUtils.currencySymbols

object CurrencyUtils {
    val currencySymbols = mapOf(
        "USD" to "US$",
        "EUR" to "€",
        "GBP" to "£",
        "JPY" to "JP¥",
        "AUD" to "A$",
        "BRL" to "R$",
        "CAD" to "CA$",
        "CNY" to "CN¥",
        "HKD" to "HK$",
        "ILS" to "₪",
        "INR" to "₹",
        "KRW" to "₩",
        "NZD" to "NZ$",
        "PHP" to "₱",
        "TWD" to "NT$",
        "VND" to "₫",
        "SEK" to "kr",
        "SGD" to "S$",
        "NOK" to "kr",
        "MXN" to "MX$",
        "RUB" to "₽",
        "ZAR" to "R",
        "TRY" to "₺",
        "DKK" to "kr",
        "PLN" to "zł",
        "THB" to "฿",
        "IDR" to "Rp",
        "HUF" to "Ft",
        "CZK" to "Kč",
        "CLP" to "CLP$",
        "AED" to "د.إ",
        "COP" to "COP$",
        "SAR" to "ر.س",
        "MYR" to "RM",
        "RON" to "lei",
        "ARS" to "AR$",
        "BDT" to "৳",
        "BHD" to "BD",
        "BND" to "BN$",
        "BOB" to "Bs.",
        "VEF" to "Bs F",
        "XOF" to "CFA",
        "CVE" to "CV$",
        "EGP" to "E£",
        "FJD" to "FJ$",
        "GHS" to "GH₵",
        "GTQ" to "Q",
        "GYD" to "G$",
        "ISK" to "kr",
        "JMD" to "J$",
        "JOD" to "JD",
        "KES" to "KSh",
        "KWD" to "KD",
        "LBP" to "L£",
        "LRD" to "L$",
        "MKD" to "ден",
        "MUR" to "MURs",
        "MVR" to "Rf",
        "NGN" to "₦",
        "PKR" to "₨",
        "PYG" to "₲",
        "QAR" to "QR",
        "LKR" to "Rs",
        "SCR" to "SR",
        "SYP" to "LS",
        "TZS" to "TSh",
        "UGX" to "USh",
        "UYU" to "U$",
        "VND" to "₫",
        "ZMW" to "ZK"
    )

    val currencyNames = mapOf(
        "USD" to "United States Dollar",
        "EUR" to "Euro",
        "GBP" to "British Pound Sterling",
        "JPY" to "Japanese Yen",
        "AUD" to "Australian Dollar",
        "CAD" to "Canadian Dollar",
        "CHF" to "Swiss Franc",
        "CNY" to "Chinese Yuan",
        "HKD" to "Hong Kong Dollar",
        "NZD" to "New Zealand Dollar",
        "SEK" to "Swedish Krona",
        "KRW" to "South Korean Won",
        "SGD" to "Singapore Dollar",
        "NOK" to "Norwegian Krone",
        "MXN" to "Mexican Peso",
        "INR" to "Indian Rupee",
        "RUB" to "Russian Ruble",
        "ZAR" to "South African Rand",
        "TRY" to "Turkish Lira",
        "BRL" to "Brazilian Real",
        "TWD" to "New Taiwan Dollar",
        "DKK" to "Danish Krone",
        "PLN" to "Polish Zloty",
        "THB" to "Thai Baht",
        "IDR" to "Indonesian Rupiah",
        "HUF" to "Hungarian Forint",
        "CZK" to "Czech Koruna",
        "ILS" to "Israeli New Shekel",
        "CLP" to "Chilean Peso",
        "PHP" to "Philippine Peso",
        "AED" to "United Arab Emirates Dirham",
        "COP" to "Colombian Peso",
        "SAR" to "Saudi Riyal",
        "MYR" to "Malaysian Ringgit",
        "RON" to "Romanian Leu",
        "UAH" to "Ukrainian Hryvnia",
        "ARS" to "Argentine Peso",
        "BDT" to "Bangladeshi Taka",
        "BHD" to "Bahraini Dinar",
        "BND" to "Brunei Dollar",
        "BOB" to "Bolivian Boliviano",
        "VEF" to "Venezuelan Bolívar",
        "XOF" to "West African CFA Franc",
        "CVE" to "Cape Verdean Escudo",
        "EGP" to "Egyptian Pound",
        "FJD" to "Fijian Dollar",
        "GHS" to "Ghanaian Cedi",
        "GTQ" to "Guatemalan Quetzal",
        "GYD" to "Guyanese Dollar",
        "ISK" to "Icelandic Krona",
        "JMD" to "Jamaican Dollar",
        "JOD" to "Jordanian Dinar",
        "KES" to "Kenyan Shilling",
        "KWD" to "Kuwaiti Dinar",
        "LBP" to "Lebanese Pound",
        "LRD" to "Liberian Dollar",
        "MKD" to "Macedonian Denar",
        "MUR" to "Mauritian Rupee",
        "MVR" to "Maldivian Rufiyaa",
        "NGN" to "Nigerian Naira",
        "PKR" to "Pakistani Rupee",
        "PYG" to "Paraguayan Guarani",
        "QAR" to "Qatari Riyal",
        "LKR" to "Sri Lankan Rupee",
        "SCR" to "Seychellois Rupee",
        "SYP" to "Syrian Pound",
        "TZS" to "Tanzanian Shilling",
        "UGX" to "Ugandan Shilling",
        "UYU" to "Uruguayan Peso",
        "VND" to "Vietnamese Dong",
        "ZMW" to "Zambian Kwacha"
    )
}

fun getCurrencySymbol(currencyCode: String): String {
    return currencySymbols[currencyCode] ?: currencyCode
}